const HOME_LOADING = 'HOME_LOADING';
const PRODUCTS_LOADED_SUCCESS = 'PRODUCTS_LOADED_SUCCESS';
const PRODUCTS_LOADED_FAILED = 'PRODUCTS_LOADED_FAILED';

export {
  HOME_LOADING,
  PRODUCTS_LOADED_SUCCESS,
  PRODUCTS_LOADED_FAILED,
};
