const CONTACT_LOADING = 'CONTACT_LOADING';
const CONTACT_SAVED_SUCCESS = 'CONTACT_SAVED_SUCCESS';
const CONTACT_SAVED_FAILED = 'CONTACT_SAVED_FAILED';
const CONTACT_UPDATE_FIELD = 'CONTACT_UPDATE_FIELD';

export {
  CONTACT_LOADING,
  CONTACT_SAVED_SUCCESS,
  CONTACT_SAVED_FAILED,
  CONTACT_UPDATE_FIELD,
};
